EXEC = Fixed

HEADR = Fixed.hpp

RM = rm -rf

CXX = c++

CXXFLAGS = -Wall -Wextra -Werror -std=c++98

SRC =	main.cpp\
		Fixed.cpp\

OBJS = ${SRC:.cpp=.o}

all : ${EXEC}

${EXEC} : ${OBJS} ${HEADR}
		${CXX} ${CXX
		
		

clean : 
		${RM} ${OBJS}

fclean : clean
		${RM} ${EXEC}

re : fclean all